### ISSUE TITLE
OE1 7 Tage no longer working

### ISSUE THREAD

**Issue by jonach66** [tischlda/mopidy-oe1#2]
It seems that some changes took place in May at OE1, and now "7 Tage" is no longer working porperly!
Pls check & fix, your apllication is very useful to me!
kr
jo

**Comment by shuber2** [comment]
I have posted a pull request #3 that adds support for the new JSON API used by Ö1.

**Comment by tischlda** [comment]
Thanks to @shuber2 the issue should be fixed now, upgrade using `pip install mopidy-oe1 --upgrade`
